# Generated by Django 4.1.3 on 2022-11-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0004_rename_usuario_items_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='user_id',
            new_name='user',
        ),
    ]
