# Generated by Django 4.1.3 on 2022-11-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ItemApp', '0006_rename_user_items_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='usuario',
            new_name='user',
        ),
    ]
